eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.245:8080/eureka/
      
server:
  port: 8767
  
spring:
  application:
    name: user-provider-service
  
    
       
jedis :  
  pool :  
    host : 192.168.1.245  
    port : 6379  
    config :  
      maxTotal: 100  
      maxIdle: 10  
      maxWaitMillis : 100000    