eureka:
  client:
    serviceUrl:
      defaultZone: http://172.16.4.218:8080/eureka/
      
server:
  port: 8767
  
spring:
  application:
    name: user-provider-service
feign:
  httpclient:
    enabled: true   